name: CI
on: [push]
jobs:
  install:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bun prepare
        uses: karpov-kir/github-actions/bun-prepare@main

  build:
    runs-on: ubuntu-24.04
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bun prepare
        uses: karpov-kir/github-actions/bun-prepare@main

      - name: Build
        run: bun run build

  lint:
    runs-on: ubuntu-24.04
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bun prepare
        uses: karpov-kir/github-actions/bun-prepare@main

      - name: Lint
        run: bun run lint

  test:
    runs-on: ubuntu-24.04
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bun prepare
        uses: karpov-kir/github-actions/bun-prepare@main

      - name: Initialize coverage cache
        uses: actions/cache@v4
        with:
          path: ./coverage
          key: ${{ runner.os }}-coverage-${{ github.sha }}

      - name: Test
        run: bun run test:ci

  analyze:
    runs-on: ubuntu-24.04
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore coverage cache 
        uses: actions/cache@v4
        with:
          path: ./coverage
          key: ${{ runner.os }}-coverage-${{ github.sha }}

      - name: SonarQube scan
        uses: karpov-kir/github-actions/sonarqube-scan@main
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          sonar-host-url: ${{ secrets.SONAR_HOST_URL }}
